"""Pure renderer for the default HA-DocGen configuration file.

Produces deterministic, fully documented YAML that matches the
:class:`~ha_docgen.config.ProjectConfig` schema consumed by
:func:`~ha_docgen.config.load_config`. Performs no filesystem access.
"""

from __future__ import annotations

from typing import Final

from ..constants import (
    FILE_AREA_REGISTRY,
    FILE_CONFIG_ENTRIES,
    FILE_DEVICE_REGISTRY,
    FILE_ENTITY_REGISTRY,
    FILE_FLOOR_REGISTRY,
    FOLDER_CUSTOM_COMPONENTS,
    FOLDER_DASHBOARDS,
    FOLDER_ESPHOME,
    FOLDER_PACKAGES,
    FOLDER_STORAGE,
    FOLDER_THEMES,
    FOLDER_WWW,
)

# Placeholder and default values aligned with ProjectConfig / load_config.
_PLACEHOLDER_PROJECT_NAME: Final[str] = "Your Project"
_PLACEHOLDER_VERSION: Final[str] = "1.0"
_PLACEHOLDER_ROOT: Final[str] = "/path/to/homeassistant/config"
_DEFAULT_CONFIGURATION: Final[str] = "configuration.yaml"
_DEFAULT_DOCS: Final[str] = "docs"
_DEFAULT_README: Final[str] = "README.md"
_DEFAULT_AI_CONTEXT: Final[str] = "AI_CONTEXT.md"
_DEFAULT_ENTITY_MAP: Final[str] = "ENTITY_MAP.md"
_DEFAULT_OUTPUT_DOCS: Final[str] = "docs/generated"
_DEFAULT_CACHE: Final[str] = ".cache/ha-docgen.json"

_STORAGE_ENTITY_REGISTRY: Final[str] = f"{FOLDER_STORAGE}/{FILE_ENTITY_REGISTRY}"
_STORAGE_DEVICE_REGISTRY: Final[str] = f"{FOLDER_STORAGE}/{FILE_DEVICE_REGISTRY}"
_STORAGE_AREA_REGISTRY: Final[str] = f"{FOLDER_STORAGE}/{FILE_AREA_REGISTRY}"
_STORAGE_FLOOR_REGISTRY: Final[str] = f"{FOLDER_STORAGE}/{FILE_FLOOR_REGISTRY}"
_STORAGE_CONFIG_ENTRIES: Final[str] = f"{FOLDER_STORAGE}/{FILE_CONFIG_ENTRIES}"


class ConfigRenderer:
    """Render the default documented configuration as plain text.

    Fully stateless: no instance state, no caching and no side effects.
    """

    def render(self) -> str:
        """Return the deterministic default ``config.yaml`` contents."""
        return (
            "# HA-DocGen — runtime configuration\n"
            "#\n"
            "# Generated by: ha-docgen init\n"
            "#\n"
            "# Edit this file before running ha-docgen.\n"
            "# Required first step: set paths.root to your Home Assistant\n"
            "# configuration directory.\n"
            "#\n"
            "# Path notes:\n"
            "# - paths.*, files.* and output.* values are resolved relative\n"
            "#   to paths.root\n"
            "# - cache.path is resolved relative to this config file when not\n"
            "#   absolute\n"
            "# - Prefer placeholders until you replace them with real values\n"
            "#\n"
            "\n"
            "# Project metadata shown in generated reports and documentation.\n"
            "project:\n"
            f"  name: {_PLACEHOLDER_PROJECT_NAME}\n"
            f'  version: "{_PLACEHOLDER_VERSION}"\n'
            "\n"
            "# Locations under the Home Assistant configuration directory.\n"
            "# All values except root are relative to root.\n"
            "paths:\n"
            "  # Absolute path to your Home Assistant config directory\n"
            "  # (required). Replace this placeholder before running.\n"
            "  # Examples:\n"
            "  #   /config\n"
            "  #   /home/user/.homeassistant\n"
            '  #   "C:/Users/You/homeassistant"\n'
            f"  root: {_PLACEHOLDER_ROOT}\n"
            "\n"
            "  # Main Home Assistant configuration file.\n"
            f"  configuration: {_DEFAULT_CONFIGURATION}\n"
            "\n"
            "  # Optional project folders (used when present).\n"
            f"  packages: {FOLDER_PACKAGES}\n"
            f"  dashboards: {FOLDER_DASHBOARDS}\n"
            f"  esphome: {FOLDER_ESPHOME}\n"
            f"  docs: {_DEFAULT_DOCS}\n"
            f"  themes: {FOLDER_THEMES}\n"
            f"  custom_components: {FOLDER_CUSTOM_COMPONENTS}\n"
            f"  www: {FOLDER_WWW}\n"
            f"  storage: {FOLDER_STORAGE}\n"
            "\n"
            "# Home Assistant registry files under .storage\n"
            "# (relative to paths.root).\n"
            "files:\n"
            f"  entity_registry: {_STORAGE_ENTITY_REGISTRY}\n"
            f"  device_registry: {_STORAGE_DEVICE_REGISTRY}\n"
            f"  area_registry: {_STORAGE_AREA_REGISTRY}\n"
            f"  floor_registry: {_STORAGE_FLOOR_REGISTRY}\n"
            f"  config_entries: {_STORAGE_CONFIG_ENTRIES}\n"
            "\n"
            "# Generated documentation and context outputs\n"
            "# (relative to paths.root).\n"
            "output:\n"
            f"  readme: {_DEFAULT_README}\n"
            f"  ai_context: {_DEFAULT_AI_CONTEXT}\n"
            f"  entity_map: {_DEFAULT_ENTITY_MAP}\n"
            "  # Directory written by the default scan and report docs\n"
            "  # command.\n"
            f"  docs: {_DEFAULT_OUTPUT_DOCS}\n"
            "\n"
            "# Incremental scan cache.\n"
            "# Relative paths are resolved beside this configuration file.\n"
            "# Absolute paths are kept as configured.\n"
            "cache:\n"
            f"  path: {_DEFAULT_CACHE}\n"
        )
