"""Unit tests for the default configuration renderer."""

from __future__ import annotations

from pathlib import Path

from ha_docgen.config import load_config
from ha_docgen.initialization import ConfigRenderer


def test_render_is_deterministic() -> None:
    """Repeated rendering produces identical output."""
    renderer = ConfigRenderer()

    assert renderer.render() == renderer.render()
    assert ConfigRenderer().render() == renderer.render()


def test_render_contains_placeholder_values() -> None:
    """Generated configuration uses placeholder values for first-run editing."""
    content = ConfigRenderer().render()

    assert "Your Project" in content
    assert 'version: "1.0"' in content
    assert "root: /path/to/homeassistant/config" in content
    assert "path: .cache/ha-docgen.json" in content


def test_render_contains_documentation_comments() -> None:
    """Generated configuration explains each section for new users."""
    content = ConfigRenderer().render()

    assert content.startswith("# HA-DocGen — runtime configuration")
    assert "Generated by: ha-docgen init" in content
    assert "set paths.root" in content
    assert "# Project metadata" in content
    assert "# Absolute path to your Home Assistant config directory" in content
    assert "# Incremental scan cache." in content


def test_render_includes_all_configuration_sections() -> None:
    """Rendered YAML exposes every section required by the config model."""
    content = ConfigRenderer().render()

    for section in ("project:", "paths:", "files:", "output:", "cache:"):
        assert f"\n{section}\n" in f"\n{content}"


def test_render_uses_lf_newlines_only() -> None:
    """Rendered text is platform-independent with Unix line endings."""
    content = ConfigRenderer().render()

    assert "\r" not in content
    assert content.endswith("\n")


def test_rendered_configuration_loads_into_project_config(tmp_path: Path) -> None:
    """Rendered output stays synchronized with the configuration model."""
    config_file = tmp_path / "config.yaml"
    config_file.write_text(ConfigRenderer().render(), encoding="utf-8", newline="\n")

    config = load_config(config_file)

    assert config.project_name == "Your Project"
    assert config.version == "1.0"
    assert config.root == Path("/path/to/homeassistant/config")
    assert config.configuration.name == "configuration.yaml"
    assert config.packages.name == "packages"
    assert config.entity_registry.name == "core.entity_registry"
    assert config.output_docs.name == "generated"
    assert config.cache == config_file.parent / ".cache/ha-docgen.json"
