"""Shared constants for HA-DocGen.

Generic filesystem constants and Home Assistant project constants.
"""

from __future__ import annotations

from .files import (
    DEFAULT_ENCODING,
    EXTENSION_JSON,
    EXTENSION_MARKDOWN,
    EXTENSION_PYTHON,
    EXTENSION_TEXT,
    GLOB_JSON,
    GLOB_MARKDOWN,
    GLOB_PYTHON,
    GLOB_TEXT,
    TEXT_FILE_EXTENSIONS,
)
from .folders import (
    DIR_GIT,
    DIR_NODE_MODULES,
    DIR_PYCACHE,
    DIR_PYTEST_CACHE,
    DIR_RUFF_CACHE,
    DIR_VENV,
    IGNORE_DIRS,
)
from .project import (
    FILE_AREA_REGISTRY,
    FILE_CONFIG_ENTRIES,
    FILE_DEVICE_REGISTRY,
    FILE_ENTITY_REGISTRY,
    FILE_FLOOR_REGISTRY,
    FILE_LABEL_REGISTRY,
    FOLDER_CUSTOM_COMPONENTS,
    FOLDER_DASHBOARDS,
    FOLDER_ESPHOME,
    FOLDER_PACKAGES,
    FOLDER_STORAGE,
    FOLDER_THEMES,
    FOLDER_WWW,
    PROJECT_FOLDERS,
    ROOT_RELATIVE,
)
from .yaml import (
    EXTENSION_YAML,
    EXTENSION_YML,
    GLOB_YAML,
    GLOB_YML,
    YAML_EXTENSIONS,
)

__all__ = [
    "DEFAULT_ENCODING",
    "DIR_GIT",
    "DIR_NODE_MODULES",
    "DIR_PYCACHE",
    "DIR_PYTEST_CACHE",
    "DIR_RUFF_CACHE",
    "DIR_VENV",
    "EXTENSION_JSON",
    "EXTENSION_MARKDOWN",
    "EXTENSION_PYTHON",
    "EXTENSION_TEXT",
    "EXTENSION_YAML",
    "EXTENSION_YML",
    "FILE_AREA_REGISTRY",
    "FILE_CONFIG_ENTRIES",
    "FILE_DEVICE_REGISTRY",
    "FILE_ENTITY_REGISTRY",
    "FILE_FLOOR_REGISTRY",
    "FILE_LABEL_REGISTRY",
    "FOLDER_CUSTOM_COMPONENTS",
    "FOLDER_DASHBOARDS",
    "FOLDER_ESPHOME",
    "FOLDER_PACKAGES",
    "FOLDER_STORAGE",
    "FOLDER_THEMES",
    "FOLDER_WWW",
    "GLOB_JSON",
    "GLOB_MARKDOWN",
    "GLOB_PYTHON",
    "GLOB_TEXT",
    "GLOB_YAML",
    "GLOB_YML",
    "IGNORE_DIRS",
    "PROJECT_FOLDERS",
    "ROOT_RELATIVE",
    "TEXT_FILE_EXTENSIONS",
    "YAML_EXTENSIONS",
]
